
title: Accessible Videos
description: Guide for beginner creators
theme: just-the-docs
url: https://AnnKruQA.github.io/Breaking-Barriers-Accessibile-Videos-2024/
aux_links:
  Template Repository: https://github.com/AnnKruQA/Breaking-Barriers-Accessibile-Videos-2024/

#Favicon
favicon_ico: "/Images/DOQATECH_favicon.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright 2024 Anna Krukowska. Distributed under the <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"
